

export const mockArtists = [
  {
    id: "1",
    name: "Sarah Johnson",
    bio: "Professional jazz vocalist with over 10 years of experience performing at weddings, corporate events, and private parties. Known for her soulful voice and extensive repertoire spanning classic jazz standards to contemporary hits.",
    categories: ["Singer", "Jazz"],
    languages: ["English", "French"],
    priceRange: "$1,000 - $2,500",
    location: "New York, NY",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    reviewCount: 127,
    availability: "Available",
    email: "sarah@example.com",
    phone: "+1 (555) 123-4567",
  },
  {
    id: "2",
    name: "Marcus Rodriguez",
    bio: "Dynamic DJ and music producer specializing in electronic dance music, hip-hop, and Latin beats. Perfect for nightclub events, festivals, and high-energy celebrations.",
    categories: ["DJ", "Producer"],
    languages: ["English", "Spanish"],
    priceRange: "$2,500 - $5,000",
    location: "Los Angeles, CA",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 89,
    availability: "Busy until March",
    email: "marcus@example.com",
    phone: "+1 (555) 234-5678",
  },
  {
    id: "3",
    name: "Elena Petrov",
    bio: "Classical ballet dancer and choreographer with training from prestigious dance academies. Offers solo performances and group choreography for elegant events and cultural celebrations.",
    categories: ["Dancer", "Choreographer"],
    languages: ["English", "Russian", "French"],
    priceRange: "$1,000 - $2,500",
    location: "Chicago, IL",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    reviewCount: 156,
    availability: "Available",
    email: "elena@example.com",
    phone: "+1 (555) 345-6789",
  },
  {
    id: "4",
    name: "David Chen",
    bio: "Motivational speaker and business consultant with expertise in leadership development and team building. Engaging presenter for corporate events, conferences, and workshops.",
    categories: ["Speaker", "Consultant"],
    languages: ["English", "Mandarin"],
    priceRange: "$5,000 - $10,000",
    location: "San Francisco, CA",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 73,
    availability: "Available",
    email: "david@example.com",
    phone: "+1 (555) 456-7890",
  },
  {
    id: "5",
    name: "Isabella Martinez",
    bio: "Stand-up comedian with a sharp wit and relatable humor. Perfect for corporate events, private parties, and entertainment venues looking for quality comedy acts.",
    categories: ["Comedian"],
    languages: ["English", "Spanish"],
    priceRange: "$500 - $1,000",
    location: "Austin, TX",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 94,
    availability: "Available",
    email: "isabella@example.com",
    phone: "+1 (555) 567-8901",
  },
  {
    id: "6",
    name: "The Harmony Quartet",
    bio: "Professional string quartet specializing in classical, contemporary, and film music. Perfect for weddings, corporate events, and intimate gatherings requiring elegant musical accompaniment.",
    categories: ["Band", "Classical"],
    languages: ["English"],
    priceRange: "$2,500 - $5,000",
    location: "Boston, MA",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 112,
    availability: "Available",
    email: "harmony@example.com",
    phone: "+1 (555) 678-9012",
  },
]

export const mockArtistSubmissions = [
  {
    id: "1",
    name: "Alex Thompson",
    email: "alex@example.com",
    phone: "+1 (555) 111-2222",
    bio: "Professional guitarist with 15 years of experience in rock, blues, and acoustic performances.",
    categories: ["Singer", "Guitarist"],
    languages: ["English"],
    priceRange: "$1,000 - $2,500",
    location: "Nashville, TN",
    status: "pending",
    submittedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "Maria Gonzalez",
    email: "maria@example.com",
    phone: "+1 (555) 222-3333",
    bio: "Flamenco dancer and instructor with traditional Spanish training and modern fusion experience.",
    categories: ["Dancer"],
    languages: ["Spanish", "English"],
    priceRange: "$2,500 - $5,000",
    location: "Miami, FL",
    status: "approved",
    submittedAt: "2024-01-14T14:20:00Z",
  },
  {
    id: "3",
    name: "James Wilson",
    email: "james@example.com",
    phone: "+1 (555) 333-4444",
    bio: "Corporate trainer and keynote speaker specializing in digital transformation and innovation.",
    categories: ["Speaker"],
    languages: ["English"],
    priceRange: "$5,000 - $10,000",
    location: "Seattle, WA",
    status: "rejected",
    submittedAt: "2024-01-13T09:15:00Z",
  },
  {
    id: "4",
    name: "Sophie Laurent",
    email: "sophie@example.com",
    phone: "+1 (555) 444-5555",
    bio: "Professional magician and illusionist with experience in close-up magic and stage performances.",
    categories: ["Magician"],
    languages: ["French", "English"],
    priceRange: "$1,000 - $2,500",
    location: "New Orleans, LA",
    status: "pending",
    submittedAt: "2024-01-12T16:45:00Z",
  },
  {
    id: "5",
    name: "The Jazz Collective",
    email: "jazz@example.com",
    phone: "+1 (555) 555-6666",
    bio: "Five-piece jazz ensemble specializing in swing, bebop, and smooth jazz for upscale events.",
    categories: ["Band", "Jazz"],
    languages: ["English"],
    priceRange: "$5,000 - $10,000",
    location: "Detroit, MI",
    status: "approved",
    submittedAt: "2024-01-11T11:30:00Z",
  },
]
